obj-y += xpmem_main.o \
	 xpmem_make.o \
	 xpmem_get.o \
	 xpmem_attach.o \
	 xpmem_signal.o \
	 xpmem_misc.o \
	 xpmem_partition.o \
	 xpmem_domain.o \
	 xpmem_hashtable.o \
	 xpmem_ns.o \
	 xpmem_fwd.o \
	 xpmem_irq.o

EXTRA_CFLAGS = -I$(obj)/include -I$(obj)/../../include/lwk/xpmem
