((nil . ((indent-tabs-mode . t))
 (c-mode . ((c-file-style . "linux")
            (indent-tabs-mode . t)
            (tab-width . 8)))
 (cc-mode . ((c-file-style . "linux")
            (indent-tabs-mode . t)
            (tab-width . 8)))))
