obj-y := \
	pmem_add.o \
	pmem_del.o \
	pmem_update.o \
	pmem_query.o \
	pmem_alloc.o \
	pmem_zero.o \
	aspace_create.o \
	aspace_destroy.o \
	aspace_get_myid.o \
	aspace_find_hole.o \
	aspace_add_region.o \
	aspace_del_region.o \
	aspace_map_pmem.o \
	aspace_unmap_pmem.o \
	aspace_smartmap.o \
	aspace_unsmartmap.o \
	aspace_dump2console.o \
	aspace_virt_to_phys.o \
	aspace_update_user_cpumask.o \
	task_create.o \
	task_switch_cpus.o \
	elf_hwcap.o \
	phys_cpu_add.o \
	phys_cpu_remove.o \
	sched_yield_task_to.o \
	sched_setparams_task.o

obj-$(CONFIG_TASK_MEAS) += task_meas.o
