BASE=../../
include $(BASE)/Makefile.header

LIBRARIES = libportals_util.a
HEADERS   = portals4_util.h

libportals_util_SOURCES = debug.c queue.c

CFLAGS += -std=gnu99

# Install in both install directories
TARGET=both

include $(BASE)/Makefile.footer
