include ../Makefile.header

LIBRARIES = libxpmem.a

libxpmem_SOURCES = xpmem.c

INCLUDES += \
	-I. \
	-I../liblwk/include \
	-I../../include \
	-I$O/../../include \
	-I$O/../../include2 \

include ../Makefile.footer
