CPPFLAGS += -Ilinux/ofed/$(CONFIG_OFED)/include
obj-$(CONFIG_INFINIBAND)	+= $(CONFIG_OFED)/drivers/infiniband/core/
obj-$(CONFIG_INFINIBAND_MTHCA)          += $(CONFIG_OFED)/drivers/infiniband/hw/mthca/
obj-$(CONFIG_MLX4_INFINIBAND)           += $(CONFIG_OFED)/drivers/infiniband/hw/mlx4/
obj-$(CONFIG_MLX4_CORE) += $(CONFIG_OFED)/drivers/net/mlx4/
