extra-y		:= head.o head64.o init_task.o vmlwk.lds
EXTRA_FLAGS	:= -traditional
obj-y		:= pda.o percpu.o setup.o e820.o cpuinfo.o resource.o \
		   mpparse.o traps.o entry.o show.o

obj-$(CONFIG_CRAY_XT) += rca/
