obj-$(CONFIG_HIO_SYSCALL) := \
	hio_open.o \
	hio_close.o \
	hio_read.o \
	hio_write.o \
	hio_mmap.o \
	hio_munmap.o \
	hio_ioctl.o \
	hio_openat.o \
	hio_getdents.o \
	hio_getdents64.o \
	hio_stat.o \
	hio_socket.o \
	hio_accept.o \
	hio_bind.o \
	hio_listen.o \
	hio_connect.o \
	hio_getsockopt.o \
	hio_setsockopt.o \
	hio_getsockname.o \
	hio_sendto.o \
	hio_recvmsg.o \
	hio_lseek.o \
	hio_fcntl.o \
	hio_uname.o \
	hio_getpid.o \
	hio_gettid.o \
	hio_newfstatat.o \
	hio_ftruncate.o \
	hio_poll.o \
	hio_recvfrom.o \
	hio_statfs.o \
	hio_set_tid_address.o

