obj-$(CONFIG_HIO_SYSCALL) := \
	hio_open.o \
	hio_close.o \
	hio_read.o \
	hio_write.o \
	hio_mmap.o \
	hio_munmap.o \
	hio_ioctl.o \
	hio_openat.o \
	hio_getdents.o \
	hio_stat.o \
	hio_socket.o \
	hio_accept.o \
	hio_bind.o \
	hio_listen.o \
	hio_connect.o \
	hio_getsockopt.o \
	hio_setsockopt.o \
	hio_getsockname.o \
	hio_sendto.o \
	hio_recvmsg.o

