obj-$(CONFIG_PISCES) += pisces_init.o \
			pisces_lock.o \
			pisces_ctrl.o \
			pisces_xbuf.o \
			hashtable.o \
			pisces_lcall.o \
			pisces_file.o \
			pisces_xpmem.o \
			pisces_pagemap.o \
			pisces_irq_proxy.o \
			pisces_pci.o


#$(obj)/pisces_guest.o :: EXTRA_CFLAGS = \
#	-I$(CONFIG_PISCES_MODULE_PATH)/inc \

