
all:
	make -C libarp
	make -C libinit_ompi
	make -C libmalloc
	make -C liblwkOrte 
	make -C libwait4net 
	make -C pct
	make -C pal
	make -C app

clean:
	make -C libarp clean
	make -C libinit_ompi clean 
	make -C libmalloc clean
	make -C liblwkOrte clean 
	make -C libwait4net clean 
	make -C pct clean
	make -C pal clean
	make -C app clean
