include ../Makefile.header

PROGRAMS = hello_world

hello_world_SOURCES = hello_world.c
hello_world_LDADD   = ../liblwk/liblwk.a -lpthread

INCLUDES += \
	-I../liblwk/include \
	-I../../include \

include ../Makefile.footer
