#
# Makefile for ACPICA Core interpreter
#

obj-y	+= acpi.o

acpi-y += tbxface.o
acpi-y += tbinstal.o
acpi-y += tbutils.o
acpi-y += tbxfroot.o

acpi-y += utalloc.o
acpi-y += utmisc.o
acpi-y += utglobal.o
acpi-y += utxferror.o

EXTRA_CFLAGS += $(ACPI_CFLAGS)
