obj-y := console.o printk.o spinlock.o params.o driver.o cpuinfo.o panic.o \
		resource.o kallsyms.o extable.o show.o elf.o time.o xcall.o \
		idspace.o htable.o elf_liblwk.o task.o sched.o
obj-y += linux_syscalls/
