obj-y := \
	console.o \
	printk.o \
	spinlock.o \
	params.o \
	driver.o \
	cpuinfo.o \
	panic.o \
	resource.o \
	kallsyms.o \
	extable.o \
	show.o \
	elf.o \
	time.o \
	xcall.o \
	elf_liblwk.o \
	task.o \
	sched.o \
	completion.o \
	waitq.o \
	timer.o \
	init_task.o \
	netdev.o \
	kfs.o \
	interrupt.o \
	semaphore.o \


obj-$(CONFIG_KGDB) += kgdb.o kgdboc.o
obj-y += linux_syscalls/
obj-y += pci/
