BASE=../../
include $(BASE)/Makefile.header

LIBRARIES = libpiapi.a
HEADERS   = piapi.h

libpiapi_SOURCES = piapi.c

CFLAGS  += -std=gnu99
INCDIRS += -I../pct
LIBDIRS += -L.

include $(BASE)/Makefile.footer
