#
# Makefile for some libs needed by the kernel.
#

lib-y := \
	vsprintf.o \
	string.o \
	cpumask.o \
	hweight.o \
	bitmap.o \
	sort.o \
	extable.o \
	ctype.o \
	idspace.o \
	htable.o \
	mutex.o \
	semaphore.o \
	rwsem-spinlock.o \
	kasprintf.o \
	kobject.o \
	kref.o \
	sysfs.o \
	sysfs-stubs.o \
