#
# Makefile for some libs needed by the kernel.
#

lib-y := \
	vsprintf.o \
	string.o \
	cpumask.o \
	hweight.o \
	bitmap.o \
	sort.o \
	extable.o \
	ctype.o \
	idspace.o \
	htable.o \
	mutex.o \
	semaphore.o \
	cmdline.o \
	sha1.o \
	sigset.o \
	siginfo.o \
