#
# Makefile for some libs needed by the kernel.
#

lib-y := \
	vsprintf.o \
	string.o \
	cpumask.o \
	hweight.o \
	bitmap.o \
	sort.o \
	extable.o \
	ctype.o \
	idspace.o \
	htable.o \
	mutex.o \
	semaphore.o \
	rwsem-spinlock.o \
	sscanf.o \
