obj-y += console/
obj-y += net/
obj-$(CONFIG_BLOCK_DEVICE) += block/

obj-$(CONFIG_KEYBOARD) += keyboard.o
obj-$(CONFIG_DEVFS) += devfs.o

obj-$(CONFIG_ACPI) += acpi/

obj-$(CONFIG_XPMEM) += xpmem/

obj-$(CONFIG_OF) += of/
 
obj-$(CONFIG_RCR) += rcr/
