obj-$(CONFIG_PC) += console/
obj-y += net/
obj-$(CONFIG_BLOCK_DEVICE) += block/

obj-$(CONFIG_KEYBOARD) += keyboard.o
obj-$(CONFIG_DEVFS) += devfs.o

obj-$(CONFIG_ACPI) += acpi/

obj-$(CONFIG_XPMEM) += xpmem/

obj-$(CONFIG_SERIAL_MM_CONSOLE) += mm_console/
obj-$(CONFIG_OF) += of/
 
obj-$(CONFIG_RCR) += rcr/
