obj-y := \
	uname.o \
	brk.o \
	write.o \
	getuid.o \
	getgid.o \
	fstat.o \
	mmap.o \
	gettimeofday.o \
	settimeofday.o \
	nanosleep.o \
	sched_yield.o \
	time.o \
	rt_sigprocmask.o \
	rt_sigaction.o \
	mprotect.o \
	clone.o \
	futex.o \

