CONFIG=../../.config
include ../Makefile.header

PROGRAMS = test_app

INCLUDES += \
	-I../liblwk/include \
	-I../../include \
	-I$O/../../include \
	-I$O/../../include2 \

test_app_SOURCES = test_app.c
#test_app_LDADD   = ../liblwk/liblwk.a -lpthread

include ../Makefile.footer
