.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PMEM_ALLOC" "2" "June 2014" "" ""
.
.SH "NAME"
\fBpmem_alloc\fR \- allocate physical memory
.
.SH "SYNOPSIS"
int pmem_alloc(size_t size, size_t alignment, const struct pmem_region \fIconstraint, struct pmem_region\fRresult);
.
.SH "DESCRIPTION"
pmem_alloc() attempts to allocate physical memory of size \fIsize\fR, aligned to \fIalignment\fR bytes and not existing in \fIcosntraint\fR physical memory\.
.
.P
This memory can then be bound into virtual memory aspace(2)es for use by user programs\.
.
.SH "RETURN VALUE"
On success 0 is returned and *result is populated by the new physical memory region\. On error, errno is returned\.
.
.SH "ERRORS"
EINVAL size is 0, alignment is 0 or not a power of two, or the pmem_region has been previously allocated\.
.
.P
ENOMEM The system was unable to find a satisfactory region of physical memory\.
