.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PMEM_ZERO" "2" "June 2014" "" ""
.
.SH "NAME"
\fBpmem_zero\fR \- zero physical memory region
.
.SH "SYNOPSIS"
int pmem_zero(const struct pmem_region *rgn);
.
.SH "DESCRIPTION"
pmem_zero() zeros a range of physical memory specified by \fIrgn\fR\.
.
.SH "RETURN VALUE"
On success 0 is returned\. On error, errno is returned\.
.
.SH "ERRORS"
EINVAL The passed region is invalid\.
