#
# Makefile for x86_64-specific library files.
#
lib-y += memmove.o memset.o memcpy.o thunk.o delay.o bitops.o extable.o usercopy.o getuser.o putuser.o
#copy_user.o
lib-y += copy_from_user.o copy_to_user.o