obj-$(CONFIG_NETWORK)		+= init.o
obj-$(CONFIG_NETWORK)		+= mem.o
obj-$(CONFIG_NETWORK)		+= memp.o
obj-$(CONFIG_NETWORK)		+= netif.o
obj-$(CONFIG_NETWORK)		+= pbuf.o
obj-$(CONFIG_NETWORK)		+= raw.o
obj-$(CONFIG_NETWORK)		+= stats.o
obj-$(CONFIG_NETWORK)		+= stats.o
obj-$(CONFIG_NETWORK)		+= sys.o
obj-$(CONFIG_NETWORK)		+= ipv4/

obj-$(CONFIG_LWIP_TCP)		+= tcp.o
obj-$(CONFIG_LWIP_TCP)		+= tcp_in.o
obj-$(CONFIG_LWIP_TCP)		+= tcp_out.o

obj-$(CONFIG_LWIP_DNS)		+= dns.o

obj-$(CONFIG_LWIP_UDP)		+= udp.o

obj-$(CONFIG_LWIP_UDP)		+= etharp.o

obj-$(CONFIG_LWIP_SOCKET)	+= api/
