include ../Makefile.header

LIBRARIES = liblwk.a

liblwk_SOURCES = syscalls.c pmem.c elf.c aspace.c

INCLUDES += \
	-Iinclude \
	-I../../include \
	-I$O/../../include \
	-I$O/../../include2 \

include ../Makefile.footer
